### ISSUE TITLE
Aur package: settings schema not installed

### ISSUE THREAD

**Issue by emersion** [bil-elmoussaoui/TwoFactorAuth#8]
```
$ twofactorauth 

(twofactorauth:15569): GLib-GIO-ERROR **: Settings schema 'org.gnome.TwoFactorAuth.login' is not installed

Trace/breakpoint trap (core dumped)
```

**Comment by bil-elmoussaoui** [comment]
Fixed! Thanks for reporting

**Comment by bil-elmoussaoui** [comment]
Btw, build files are now available in `build` branch https://github.com/bil-elmoussaoui/TwoFactorAuth/tree/build

**Comment by emersion** [comment]
Still getting the same error...

**Comment by bil-elmoussaoui** [comment]
Should be fixed now

**Comment by emersion** [comment]
Yes, thanks :)

**Comment by kennethdhau** [comment]
Not to revive this, but at least the installation on the AUR (gnome-twofactorauth | no git) still presents this issue, at least for myself.

**Comment by bil-elmoussaoui** [comment]
@kennethdhau It's normal, i need to push a new version as the fix was on the PKGBUILD and the `autogen.sh` file

**Comment by bil-elmoussaoui** [comment]
@kennethdhau Just to let you know, i've released a beta 3 that should fix your issue :+1:
